// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ValasztasDbContext))]
    [Migration("20240925092648_sqlite.local_migration_243")]
    partial class sqlitelocal_migration_243
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WebApplication1.Models.Jelolt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kerulet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartRovidNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SzavazatokSzama")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartRovidNev");

                    b.ToTable("Jeloltek");
                });

            modelBuilder.Entity("WebApplication1.Models.Part", b =>
                {
                    b.Property<string>("RovidNev")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeljesNev")
                        .HasColumnType("TEXT");

                    b.HasKey("RovidNev");

                    b.ToTable("Partok");
                });

            modelBuilder.Entity("WebApplication1.Models.Jelolt", b =>
                {
                    b.HasOne("WebApplication1.Models.Part", "Part")
                        .WithMany("Jeloltek")
                        .HasForeignKey("PartRovidNev")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("WebApplication1.Models.Part", b =>
                {
                    b.Navigation("Jeloltek");
                });
#pragma warning restore 612, 618
        }
    }
}
